spring:
  application:
    name: bcts-config
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zcloudfly/bcts.git
          search-paths: bcts-config/config-repository
          username: 920869693@qq.com
          password: zhangyunfei222
#  zipkin:
#    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info